---
- name: R ppa key
  apt_key: id="{{ cran_ppa_key }}" state=present keyserver=keyserver.ubuntu.com
- name: R ppa
  apt_repository: repo='deb {{ cran_url }}/bin/linux/ubuntu trusty/' state=present update_cache=yes
- name: R
  apt: pkg={{ item }} state=present
  with_items:
    - r-recommended
    - r-cran-rjava
