---
- user: name=gollum system=yes state=present
- name: Install Gollum init script
  template: src=systemd/gollum.service.j2 dest=/lib/systemd/system/gollum-3d-e-chem.service mode=u+rw,go+r
- name: Install git
  apt: pkg=git state=present
- name: Cloning Github wiki
  git: repo="{{ wiki_clone_url }}" dest=/opt/wiki-3d-e-chem
- name: Change ownership of wiki
  file: path=/opt/wiki-3d-e-chem owner=gollum state=directory recurse=yes
  notify:
  - restart gollum
- name: Start Gollum
  service: name=gollum-3d-e-chem state=started enabled=yes
