---
- name: Latest pip
  pip: name=pip state=latest
- name: Latest setuptools
  pip: name=setuptools state=latest
- name: Numpy
  pip: name=numpy
# TODO change to release version when possible
- name: KripoDB
  pip: name='git+hhttps://github.com/3D-e-Chem/kripodb.git' editable=false
