- name: /data/kripo/pdb directory
  file: path=/data/kripo/pdb state=directory
- name: PDB fragment sample data
  command: /usr/bin/wget -N {{ kripo_dataset_pdb }}
  args:
    chdir: /data/kripo/pdb/
