---
- name: Sample data
  get_url: url=https://github.com/3D-e-Chem/kripodb/blob/{{ kripodb_version }}/data/{{ item }}?raw=true dest=/data/kripo/tiny
  with_items:
    - fragments.sqlite
    - fingerprints.sqlite
    - distances.h5