language: python
sudo: false
cache: pip
install:
- pip install ansible
- wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip && unzip packer_0.10.1_linux_amd64.zip
script:
- ansible-playbook -i localhost, --syntax-check playbook.yml
- ./packer validate -syntax-only packer.json
