# Site settings
title: 3D-e-Chem VM
description: Virtual machine with all software and sample data to run 3D-e-Chem Knime workflows
baseurl: /3D-e-Chem-VM/
project_url: http://3d-e-chem.github.io

# Build settings
markdown: kramdown
