---
- hosts: all
  roles:
    - bootstrap
    - wiki
    - self-upgrade
    - knime
    - modifiedtanimoto
    - gpcrdb
    - kripo
  tasks:
    - name: Vagrant owns Knime
      file: path=/opt/knime state=directory recurse=yes owner=vagrant group=vagrant

