---
- hosts: all
  roles:
    - bootstrap
    - wiki
    - self-upgrade
    - knime
    - modifiedtanimoto
    - gpcrdb
    - kripo
    - sstea
    - chemdb4vs
    - klifs
  tasks:
    - name: Vagrant owns Knime
      file: path=/opt/knime state=directory recurse=yes owner=vagrant group=vagrant
    - name: Vagrant owns Knime workspace examples
      file: path='{{ knime_examples_root }}' state=directory recurse=yes owner=vagrant group=vagrant
    - name: Vagrant owns Knime workspace workflows
      file: path='{{ knime_workflows_root }}' state=directory recurse=yes owner=vagrant group=vagrant
