---
- hosts: all
  roles:
    - bootstrap
    - wiki
    - self-upgrade
    - knime
    - modifiedtanimoto
    - gpcrdb
    - kripo
  tasks:
    - name: Vagrant owns Knime
      file: path=/opt/knime state=directory recurse=yes owner=vagrant group=vagrant
    - name: Vagrant owns Knime examples
      file: path=/home/vagrant/knime-workspace/3D-e-Chem-Examples state=directory recurse=yes owner=vagrant group=vagrant

