---
- hosts: all
  roles:
    - bootstrap
    - knime
    - lxde
    - wiki
    - virtualbox-guest-additions
    - fpocket
    - r
    - self-upgrade
    - postgresql
    - rdkit
    - chembl
  tasks:
    - name: chem tools
      apt: pkg={{ item }} state=latest
      with_items:
        - openbabel
        - openbabel-gui
        - python-openbabel
        - libchemistry-openbabel-perl
        - viewmol
        - xdrawchem
    - name: apt clean
      command: apt-get clean -y
    - name: Zerofree
      shell: dd if=/dev/zero of=/EMPTY bs=100M || rm -f /EMPTY || sync
