---
- hosts: all
  roles:
    - bootstrap
    - wiki
    - self-upgrade
    - knime
    - modifiedtanimoto
    - gpcrdb
    - kripo
    - sstea
    - plants
    - silicosit
    - klifs
    - sygma
    - molviewer
    - silicosit
  tasks:
    - name: Vagrant owns KNIME
      file: path=/opt/knime state=directory recurse=yes owner=vagrant group=vagrant
    - name: Vagrant owns KNIME workspace
      file: path='{{ knime_workspace_root }}' state=directory recurse=yes owner=vagrant group=vagrant
