---
- name: Base directory
  file: path=/opt/rdkit state=directory
- name: Dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - flex
    - bison
    - build-essential
    - python-numpy
    - cmake
    - python-dev
    - sqlite3
    - libsqlite3-dev
    - libboost-dev
    - libboost-python-dev
    - libboost-regex-dev
    - libboost-serialization-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libpq-dev
    - postgresql-server-dev-9.3
- name: Fetch release
  get_url: url=https://github.com/rdkit/rdkit/archive/Release_{{ rdkit_version }}.tar.gz
    dest=/opt/rdkit/ mode=0440
- name: Unpack release
  unarchive: src=/opt/rdkit/rdkit-Release_{{ rdkit_version }}.tar.gz
    dest=/opt/rdkit copy=no creates=/opt/rdkit/rdkit-Release_{{ rdkit_version }}
- name: Build directory
  file: path=/opt/rdkit/rdkit-Release_{{ rdkit_version }}/build state=directory
- name: Add INCHI support
  command: ./download-inchi.sh
  args:
    chdir: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/External/INCHI-API/
    creates: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/External/INCHI-API/src
- name: Configure
  command: cmake -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_INSTALL_INTREE=OFF ..
  args:
    chdir: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/build
    creates: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/build/Makefile
- name: Build & Install
  command: make install
  args:
    chdir: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/build
    creates: /usr/local/lib/libRDGeneral.so.1.{{ rdkit_version|replace("_", ".") }}
- name: Postgresql cartridge
  shell: RDBASE=/opt/rdkit/rdkit-Release_{{ rdkit_version }} USE_INCHI=1 make install
  args:
    chdir: /opt/rdkit/rdkit-Release_{{ rdkit_version }}/Code/PgSQL/rdkit
    creates: /usr/lib/postgresql/9.3/lib/rdkit.so
- name: Restart postgresql
  service: name=postgresql state=restarted
- name: Update ld config
  command: ldconfig
- name: Clean up
  file: path=/opt/rdkit state=absent