---
# These tasks installs the knime analytics platform.
- name: Install swt browser widget for knime internal browser
  apt: pkg=libwebkitgtk-1.0-0 state=present
- get_url: url=http://download.knime.org/analytics-platform/linux/knime-full_{{ knime_version }}.linux.gtk.x86_64.tar.gz dest=/opt/knime-{{ knime_version }}.tar.gz mode=0440
- file: path=/opt/knime state=directory mode=0755
- unarchive: src=/opt/knime-{{ knime_version }}.tar.gz dest=/opt/knime copy=no creates=/opt/knime/knime-full_{{ knime_version }}
- file: src=/opt/knime/knime-full_{{ knime_version }}/knime dest=/usr/bin/knime state=link
- file: path=/opt/knime-{{ knime_version }}.tar.gz state=absent
# Clean up old Knime
- file: path=/opt/knime.tar.gz state=absent
- file: path=/opt/knime/knime-full_2.12.0 state=absent
