---
knime_version: 3.1.2
knime_root: /opt/knime/knime-full_{{ knime_version }}
knime_repositories: https://3d-e-chem.github.io/updates
knime_examples_root: /home/vagrant/knime-workspace/3D-e-Chem-Examples
knime_nr_of_examples: 5
knime_workflows_root: /home/vagrant/knime-workspace/3D-e-Chem-Workflows
knime_nr_of_workflows: 2
