---
- name: Install GPCRDB nodes
  command: /usr/bin/knime_plugin_installer.sh nl.esciencecenter.e3dchem.gpcrdb {{knime_repositories}}
  args:
    creates: "{{ knime_root }}/nl.esciencecenter.e3dchem.gpcrdb"
- name: Knime example workflow for GPCRDB nodes
  unarchive: src={{ example_url}} dest={{ knime_examples_root }} creates={{ example_dir }} copy=no
