---
- name: Knime example workflow for GPCRDB nodes
  unarchive: src={{ example_url}} dest={{ knime_examples_root }} copy=no
- name: Remove /data/gpcrdb Directory
  file: path=/data/gpcrdb state=absent
