---
- name: Install latest GPCRDB nodes
  command: /usr/bin/knime_plugin_installer.sh nl.esciencecenter.e3dchem.gpcrdb {{knime_repositories}}
- name: Knime example workflow for GPCRDB nodes
  unarchive: src={{ example_url}} dest={{ knime_examples_root }} copy=no
